server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    driver-class-name: org.postgresql.Driver
    password: secure_password
    username: postgres